### PR TITLE
Added AADT_factors

### PR DESCRIPTION
**Pull request by juanfonsecaLS1**

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]
Looks good to me Juan, many thanks! One minor comment: would be easier to read and make no difference to the results if the numbers were less precise e.g. to the nearest 10,000th (4 decimal places) would be fine and could be achieved with

```r
aadt_factors = round(aadt_factors, 4)
```

or similar. Overall big thumbs up  from me. @mem48 and @joeytalbot thoughts?

**Comment by juanfonsecaLS1** [comment]
The numbers are trip rates for an average adult on employment (commute) and for a average adult (all other purposes), so they are meant to be used as a factor to get the Average Annual Daily Flows.
image
 The bike ones are the ones to be applied in the base_line scenario (no mode shift assumed) i.e. to obtain the number of trips made by people who currently use the bike. The AADT_all are the ones for the other scenarios, where mode shift is expected as they were derived for all other modes, the main assumption is that trip frequency will be the same if they switch to bike. 
I hope that is more clear.
If I guess that the other two columns are just a sense check not to be used in the built.

**Comment by juanfonsecaLS1** [comment]
yes you are right, that is to convert to AADT.

**Comment by juanfonsecaLS1** [comment]
Just to clarify, the only one that is subset-based is commute (employed people). The others are adult population

**Comment by juanfonsecaLS1** [comment]
Probably this will make more sense:

| Purpose              | AADT_bike                                                                                          |
|----------------------|----------------------------------------------------------------------------------------------------|
| Commute              | Daily avg of bike commute trips made by an employed adults who already uses the bike      |
| Leisure              | Daily avg of bike leisure trips made by an adult who already uses the bike  |
| Visiting             | Daily avg of bike trips for visiting made by adult who already uses the bike |
| Recreational Cycling | Daily avg of 'recreational cycling' trips made by adult who already uses the bike |
| Other                | Daily avg of 'Other purposes' trips made by adult who already uses the bike  |


| Purpose              | AADT_all                                                                                          |
|----------------------|----------------------------------------------------------------------------------------------------|
| Commute              | Daily avg of commute trips made by an employed adult      |
| Leisure              | Daily avg of leisure trips made by an adult   |
| Visiting             | Daily avg of trips for visiting made by an adult  |
| Recreational Cycling | Daily avg of 'recreational cycling' trips made by an adult  |
| Other                | Daily avg of 'Other purposes' trips made by an adult  |

The recreational cycling purpose is exclusive for bike rides i.e. "going for a ride", not all recreational purposes as walks and day trips.

**Comment by juanfonsecaLS1** [comment]
Yes, this is correct.

**Comment by juanfonsecaLS1** [comment]
Although, all estimates have been calculated for the 7 days of the week as that how it was reported in the SHS

**Comment by Robinlovelace** [comment]
Reading this thread with interest. I think we can convert these numbers into whichever units make most sense. The key think I think is that the total number of trips add up to total number of trips in a typical day, averaged over the year. Sense checking this for each mode:

- For commuting, this means typical weekday trips x "Daily avg of commute trips made by an employed adult" in the table
- For leisure, this means that we ensure that there are "Daily avg of leisure trips made by an adult" x number of adults originating in each zone in the table
- For school trips... not quite sure

**Pull request merged**
