### PR TITLE
Parallel full build tests2

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
FYI re-running full build attempt after upstream change to CycleStreets prevents timeout, hopefully.

**Comment by Robinlovelace** [comment]
Update on this, RStudio seems to have crashed overnight:

image

**Comment by Robinlovelace** [comment]
Seems to have crashed on the 2nd commute one. Could it be due to having in memory 2 huge route objects? I suspect that having only 1 worker will fix this @mem48 but will try again with 2 workers to finish the experiment. Result so far: code on this branch does not work for full build.

image

**Comment by Robinlovelace** [comment]
Restarted the computer, trying again.

**Comment by Robinlovelace** [comment]
Good thing about targets: re-starts wherever it got to previously.

image

**Comment by mem48** [comment]
Closing as these fixes have already been added to the branch

**Comment by Robinlovelace** [comment]
Heads-up @mem48 I've just deleted the branch. Please always delete branches after merging/closing PRs to tidy up repos.

**Pull request closed without merging**
