### PR TITLE
Try with 250 routes and new routes

### PR DESCRIPTION
**Pull request by atumscott**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @wangzhao0217 it worked with a mimal build with max at 250. Now going to try a full build.

**Comment by Robinlovelace** [comment]
image

**Comment by Robinlovelace** [comment]
@mvl22 we're seeing this message a lot, any ideas, R side or CycleStreets side most likely?

```
    Timeout was reached: [api.cyclestreets.net] SSL connection timeout
```

**Comment by Robinlovelace** [comment]
It fails intermittently, the 60k job is now done:

```
● completed target rs_school_fastest [19.172 minutes]
```

**Comment by mvl22** [comment]
Why are you using that endpoint rather than your dedicated one?

**Comment by Robinlovelace** [comment]
> Why are you using that endpoint rather than your dedicated one?

I think it *is* using the dedicated server.

**Comment by Robinlovelace** [comment]
Latest error : ( this is not very fail safe. cc @mem48 

```
✖ errored target rs_commute_fastest
✖ errored pipeline [3.924 hours]
Warning message:
6 targets produced warnings. Run targets::tar_meta(fields = warnings, complete_only = TRUE) for the messages. 
Error:
! Error running targets::tar_make()
Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
Debugging guide: https://books.ropensci.org/targets/debugging.html
How to ask for help: https://books.ropensci.org/targets/help.html
Last error message:
    UNCLOSED_STRING: A string is opened, but never closed.
Last error traceback:
    get_routes(od = od_commute_subset, plans = "fastest", purpose = "commute...
    cyclestreets::batch(desire_lines = od, wait = TRUE, maxDistance = 30000,...
    get_routes(url = res_joburls$dataGz, desire_lines, filename,      direct...
    batch_read(filename_local, cols_to_keep = cols_to_keep, segments = segme...
    json2sf_cs(results_raw = res$json, id = res$route_number, segments = seg...
    RcppSimdJson::fparse(results_raw, query = "/marker", query_error_ok = TR...
    .deserialize_json(json = json, query = query, empty_array = empty_array,...
    .handleSimpleError(function (condition)  {     state$error <- build_mess...
    h(simpleError(msg, call))
```

**Comment by Robinlovelace** [comment]
Think out loud / while typing: it's a bit high stakes to do all of Scotland in 1 go. Latest thought: regionalise / county-by-county would be a logical solution I think.

**Comment by mvl22** [comment]
The domain given in ‘Timeout was reached’ is not your endpoint. What functionality in the code is that error message coming from?

**Comment by mem48** [comment]
I have pointed out this before #261. The should be one target for sending jobs to cyclestreets, another for downloading results, and a third for reading them in. That was you can recover if any step fails

**Comment by Robinlovelace** [comment]
@mem48 can you try the following and let us know if you get an error?

The issue is that the batches are too big: when we download the files (as we currently do although to a generic place in tempdir not a well-named file) that's not much help if part of the file is corrupt for whatever reason.

**Pull request closed without merging**
