### PR TITLE
merge test

### PR DESCRIPTION
**Pull request by wangzhao0217**

### CODE REVIEW

**Review by Robinlovelace — CHANGES_REQUESTED** [review]
Hi @wangzhao0217 looks good.

Can you move `merge_test.qmd` into the `code/tests` folder?

**Comment by wangzhao0217** [comment]
Done Robin.

**Review by Robinlovelace — APPROVED** [review]
Great job. This is good to go. Please merge and delete the old branch @wangzhao0217 :tada:

**Comment by Robinlovelace** [comment]
And final step @wangzhao0217: deleting the branch. You should see a button near the bottom of this page to do that (in case you get this notification by email, I turn off emails and focus on the website for notifications FYI): https://github.com/nptscot/npt/pull/296#event-10664200722

**Pull request merged**
